// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cookieBanner.proto
// Protobuf C++ Version: 6.32.1

#ifndef cookieBanner_2eproto_2epb_2eh
#define cookieBanner_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cookieBanner_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cookieBanner_2eproto {
  static const ::uint32_t offsets[];
};
namespace mozilla {
namespace cookieBanner {
class GoogleSOCSCookie;
struct GoogleSOCSCookieDefaultTypeInternal;
extern GoogleSOCSCookieDefaultTypeInternal _GoogleSOCSCookie_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<38> GoogleSOCSCookie_class_data_;
class GoogleSOCSCookie_extraData;
struct GoogleSOCSCookie_extraDataDefaultTypeInternal;
extern GoogleSOCSCookie_extraDataDefaultTypeInternal _GoogleSOCSCookie_extraData_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<48> GoogleSOCSCookie_extraData_class_data_;
class GoogleSOCSCookie_timeData;
struct GoogleSOCSCookie_timeDataDefaultTypeInternal;
extern GoogleSOCSCookie_timeDataDefaultTypeInternal _GoogleSOCSCookie_timeData_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<47> GoogleSOCSCookie_timeData_class_data_;
}  // namespace cookieBanner
}  // namespace mozilla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mozilla {
namespace cookieBanner {

// ===================================================================


// -------------------------------------------------------------------

class GoogleSOCSCookie_timeData final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:mozilla.cookieBanner.GoogleSOCSCookie.timeData) */ {
 public:
  inline GoogleSOCSCookie_timeData() : GoogleSOCSCookie_timeData(nullptr) {}
  ~GoogleSOCSCookie_timeData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GoogleSOCSCookie_timeData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GoogleSOCSCookie_timeData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GoogleSOCSCookie_timeData(::google::protobuf::internal::ConstantInitialized);

  inline GoogleSOCSCookie_timeData(const GoogleSOCSCookie_timeData& from) : GoogleSOCSCookie_timeData(nullptr, from) {}
  inline GoogleSOCSCookie_timeData(GoogleSOCSCookie_timeData&& from) noexcept
      : GoogleSOCSCookie_timeData(nullptr, ::std::move(from)) {}
  inline GoogleSOCSCookie_timeData& operator=(const GoogleSOCSCookie_timeData& from) {
    CopyFrom(from);
    return *this;
  }
  inline GoogleSOCSCookie_timeData& operator=(GoogleSOCSCookie_timeData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const GoogleSOCSCookie_timeData& default_instance() {
    return *reinterpret_cast<const GoogleSOCSCookie_timeData*>(
        &_GoogleSOCSCookie_timeData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GoogleSOCSCookie_timeData& a, GoogleSOCSCookie_timeData& b) { a.Swap(&b); }
  inline void Swap(GoogleSOCSCookie_timeData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GoogleSOCSCookie_timeData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GoogleSOCSCookie_timeData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<GoogleSOCSCookie_timeData>(arena);
  }
  void CopyFrom(const GoogleSOCSCookie_timeData& from);
  void MergeFrom(const GoogleSOCSCookie_timeData& from) { GoogleSOCSCookie_timeData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GoogleSOCSCookie_timeData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozilla.cookieBanner.GoogleSOCSCookie.timeData"; }

 protected:
  explicit GoogleSOCSCookie_timeData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GoogleSOCSCookie_timeData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GoogleSOCSCookie_timeData& from);
  GoogleSOCSCookie_timeData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GoogleSOCSCookie_timeData&& from) noexcept
      : GoogleSOCSCookie_timeData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeStampFieldNumber = 1,
  };
  // required uint64 timeStamp = 1;
  bool has_timestamp() const;
  void clear_timestamp() ;
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GoogleSOCSCookie_timeData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cookieBanner_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<47> GoogleSOCSCookie_timeData_class_data_;
// -------------------------------------------------------------------

class GoogleSOCSCookie_extraData final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:mozilla.cookieBanner.GoogleSOCSCookie.extraData) */ {
 public:
  inline GoogleSOCSCookie_extraData() : GoogleSOCSCookie_extraData(nullptr) {}
  ~GoogleSOCSCookie_extraData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GoogleSOCSCookie_extraData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GoogleSOCSCookie_extraData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GoogleSOCSCookie_extraData(::google::protobuf::internal::ConstantInitialized);

  inline GoogleSOCSCookie_extraData(const GoogleSOCSCookie_extraData& from) : GoogleSOCSCookie_extraData(nullptr, from) {}
  inline GoogleSOCSCookie_extraData(GoogleSOCSCookie_extraData&& from) noexcept
      : GoogleSOCSCookie_extraData(nullptr, ::std::move(from)) {}
  inline GoogleSOCSCookie_extraData& operator=(const GoogleSOCSCookie_extraData& from) {
    CopyFrom(from);
    return *this;
  }
  inline GoogleSOCSCookie_extraData& operator=(GoogleSOCSCookie_extraData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const GoogleSOCSCookie_extraData& default_instance() {
    return *reinterpret_cast<const GoogleSOCSCookie_extraData*>(
        &_GoogleSOCSCookie_extraData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GoogleSOCSCookie_extraData& a, GoogleSOCSCookie_extraData& b) { a.Swap(&b); }
  inline void Swap(GoogleSOCSCookie_extraData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GoogleSOCSCookie_extraData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GoogleSOCSCookie_extraData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<GoogleSOCSCookie_extraData>(arena);
  }
  void CopyFrom(const GoogleSOCSCookie_extraData& from);
  void MergeFrom(const GoogleSOCSCookie_extraData& from) { GoogleSOCSCookie_extraData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GoogleSOCSCookie_extraData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozilla.cookieBanner.GoogleSOCSCookie.extraData"; }

 protected:
  explicit GoogleSOCSCookie_extraData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GoogleSOCSCookie_extraData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GoogleSOCSCookie_extraData& from);
  GoogleSOCSCookie_extraData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GoogleSOCSCookie_extraData&& from) noexcept
      : GoogleSOCSCookie_extraData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlatformFieldNumber = 2,
    kRegionFieldNumber = 3,
    kUnused1FieldNumber = 1,
    kUnused2FieldNumber = 4,
  };
  // required string platform = 2;
  bool has_platform() const;
  void clear_platform() ;
  const ::std::string& platform() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_platform(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_platform();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_platform();
  void set_allocated_platform(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_platform() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_platform(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_platform();

  public:
  // required string region = 3;
  bool has_region() const;
  void clear_region() ;
  const ::std::string& region() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_region(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_region();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_region();
  void set_allocated_region(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_region() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_region(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_region();

  public:
  // required uint32 unused1 = 1;
  bool has_unused1() const;
  void clear_unused1() ;
  ::uint32_t unused1() const;
  void set_unused1(::uint32_t value);

  private:
  ::uint32_t _internal_unused1() const;
  void _internal_set_unused1(::uint32_t value);

  public:
  // required uint32 unused2 = 4;
  bool has_unused2() const;
  void clear_unused2() ;
  ::uint32_t unused2() const;
  void set_unused2(::uint32_t value);

  private:
  ::uint32_t _internal_unused2() const;
  void _internal_set_unused2(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GoogleSOCSCookie_extraData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr platform_;
    ::google::protobuf::internal::ArenaStringPtr region_;
    ::uint32_t unused1_;
    ::uint32_t unused2_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cookieBanner_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<48> GoogleSOCSCookie_extraData_class_data_;
// -------------------------------------------------------------------

class GoogleSOCSCookie final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:mozilla.cookieBanner.GoogleSOCSCookie) */ {
 public:
  inline GoogleSOCSCookie() : GoogleSOCSCookie(nullptr) {}
  ~GoogleSOCSCookie() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GoogleSOCSCookie* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GoogleSOCSCookie));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GoogleSOCSCookie(::google::protobuf::internal::ConstantInitialized);

  inline GoogleSOCSCookie(const GoogleSOCSCookie& from) : GoogleSOCSCookie(nullptr, from) {}
  inline GoogleSOCSCookie(GoogleSOCSCookie&& from) noexcept
      : GoogleSOCSCookie(nullptr, ::std::move(from)) {}
  inline GoogleSOCSCookie& operator=(const GoogleSOCSCookie& from) {
    CopyFrom(from);
    return *this;
  }
  inline GoogleSOCSCookie& operator=(GoogleSOCSCookie&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const GoogleSOCSCookie& default_instance() {
    return *reinterpret_cast<const GoogleSOCSCookie*>(
        &_GoogleSOCSCookie_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GoogleSOCSCookie& a, GoogleSOCSCookie& b) { a.Swap(&b); }
  inline void Swap(GoogleSOCSCookie* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GoogleSOCSCookie* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GoogleSOCSCookie* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<GoogleSOCSCookie>(arena);
  }
  void CopyFrom(const GoogleSOCSCookie& from);
  void MergeFrom(const GoogleSOCSCookie& from) { GoogleSOCSCookie::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GoogleSOCSCookie* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozilla.cookieBanner.GoogleSOCSCookie"; }

 protected:
  explicit GoogleSOCSCookie(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GoogleSOCSCookie(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GoogleSOCSCookie& from);
  GoogleSOCSCookie(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GoogleSOCSCookie&& from) noexcept
      : GoogleSOCSCookie(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using extraData = GoogleSOCSCookie_extraData;
  using timeData = GoogleSOCSCookie_timeData;

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kTimeFieldNumber = 3,
    kGdprChoiceFieldNumber = 1,
  };
  // required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
  bool has_data() const;
  void clear_data() ;
  const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData& data() const;
  [[nodiscard]] ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE release_data();
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NONNULL mutable_data();
  void set_allocated_data(::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_data(::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE value);
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE unsafe_arena_release_data();

  private:
  const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData& _internal_data() const;
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
  bool has_time() const;
  void clear_time() ;
  const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData& time() const;
  [[nodiscard]] ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE release_time();
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NONNULL mutable_time();
  void set_allocated_time(::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_time(::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE value);
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE unsafe_arena_release_time();

  private:
  const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData& _internal_time() const;
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NONNULL _internal_mutable_time();

  public:
  // required uint32 gdpr_choice = 1;
  bool has_gdpr_choice() const;
  void clear_gdpr_choice() ;
  ::uint32_t gdpr_choice() const;
  void set_gdpr_choice(::uint32_t value);

  private:
  ::uint32_t _internal_gdpr_choice() const;
  void _internal_set_gdpr_choice(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozilla.cookieBanner.GoogleSOCSCookie)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GoogleSOCSCookie& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE data_;
    ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE time_;
    ::uint32_t gdpr_choice_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cookieBanner_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<38> GoogleSOCSCookie_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GoogleSOCSCookie_extraData

// required uint32 unused1 = 1;
inline bool GoogleSOCSCookie_extraData::has_unused1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void GoogleSOCSCookie_extraData::clear_unused1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unused1_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::uint32_t GoogleSOCSCookie_extraData::unused1() const {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.extraData.unused1)
  return _internal_unused1();
}
inline void GoogleSOCSCookie_extraData::set_unused1(::uint32_t value) {
  _internal_set_unused1(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.extraData.unused1)
}
inline ::uint32_t GoogleSOCSCookie_extraData::_internal_unused1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unused1_;
}
inline void GoogleSOCSCookie_extraData::_internal_set_unused1(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unused1_ = value;
}

// required string platform = 2;
inline bool GoogleSOCSCookie_extraData::has_platform() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void GoogleSOCSCookie_extraData::clear_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& GoogleSOCSCookie_extraData::platform() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.extraData.platform)
  return _internal_platform();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GoogleSOCSCookie_extraData::set_platform(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.platform_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.extraData.platform)
}
inline ::std::string* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::mutable_platform()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_platform();
  // @@protoc_insertion_point(field_mutable:mozilla.cookieBanner.GoogleSOCSCookie.extraData.platform)
  return _s;
}
inline const ::std::string& GoogleSOCSCookie_extraData::_internal_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.platform_.Get();
}
inline void GoogleSOCSCookie_extraData::_internal_set_platform(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.platform_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::_internal_mutable_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.platform_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GoogleSOCSCookie_extraData::release_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.cookieBanner.GoogleSOCSCookie.extraData.platform)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.platform_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.platform_.Set("", GetArena());
  }
  return released;
}
inline void GoogleSOCSCookie_extraData::set_allocated_platform(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.platform_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.platform_.IsDefault()) {
    _impl_.platform_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.extraData.platform)
}

// required string region = 3;
inline bool GoogleSOCSCookie_extraData::has_region() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void GoogleSOCSCookie_extraData::clear_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.region_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& GoogleSOCSCookie_extraData::region() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.extraData.region)
  return _internal_region();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GoogleSOCSCookie_extraData::set_region(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.region_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.extraData.region)
}
inline ::std::string* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::mutable_region()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_region();
  // @@protoc_insertion_point(field_mutable:mozilla.cookieBanner.GoogleSOCSCookie.extraData.region)
  return _s;
}
inline const ::std::string& GoogleSOCSCookie_extraData::_internal_region() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.region_.Get();
}
inline void GoogleSOCSCookie_extraData::_internal_set_region(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.region_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::_internal_mutable_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.region_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GoogleSOCSCookie_extraData::release_region() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.cookieBanner.GoogleSOCSCookie.extraData.region)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.region_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.region_.Set("", GetArena());
  }
  return released;
}
inline void GoogleSOCSCookie_extraData::set_allocated_region(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.region_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.region_.IsDefault()) {
    _impl_.region_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.extraData.region)
}

// required uint32 unused2 = 4;
inline bool GoogleSOCSCookie_extraData::has_unused2() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void GoogleSOCSCookie_extraData::clear_unused2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unused2_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::uint32_t GoogleSOCSCookie_extraData::unused2() const {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.extraData.unused2)
  return _internal_unused2();
}
inline void GoogleSOCSCookie_extraData::set_unused2(::uint32_t value) {
  _internal_set_unused2(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.extraData.unused2)
}
inline ::uint32_t GoogleSOCSCookie_extraData::_internal_unused2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unused2_;
}
inline void GoogleSOCSCookie_extraData::_internal_set_unused2(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unused2_ = value;
}

// -------------------------------------------------------------------

// GoogleSOCSCookie_timeData

// required uint64 timeStamp = 1;
inline bool GoogleSOCSCookie_timeData::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void GoogleSOCSCookie_timeData::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t GoogleSOCSCookie_timeData::timestamp() const {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.timeData.timeStamp)
  return _internal_timestamp();
}
inline void GoogleSOCSCookie_timeData::set_timestamp(::uint64_t value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.timeData.timeStamp)
}
inline ::uint64_t GoogleSOCSCookie_timeData::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void GoogleSOCSCookie_timeData::_internal_set_timestamp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// -------------------------------------------------------------------

// GoogleSOCSCookie

// required uint32 gdpr_choice = 1;
inline bool GoogleSOCSCookie::has_gdpr_choice() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void GoogleSOCSCookie::clear_gdpr_choice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gdpr_choice_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::uint32_t GoogleSOCSCookie::gdpr_choice() const {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.gdpr_choice)
  return _internal_gdpr_choice();
}
inline void GoogleSOCSCookie::set_gdpr_choice(::uint32_t value) {
  _internal_set_gdpr_choice(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:mozilla.cookieBanner.GoogleSOCSCookie.gdpr_choice)
}
inline ::uint32_t GoogleSOCSCookie::_internal_gdpr_choice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gdpr_choice_;
}
inline void GoogleSOCSCookie::_internal_set_gdpr_choice(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gdpr_choice_ = value;
}

// required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
inline bool GoogleSOCSCookie::has_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline void GoogleSOCSCookie::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData& GoogleSOCSCookie::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData&>(::mozilla::cookieBanner::_GoogleSOCSCookie_extraData_default_instance_);
}
inline const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData& GoogleSOCSCookie::data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.data)
  return _internal_data();
}
inline void GoogleSOCSCookie::unsafe_arena_set_allocated_data(
    ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_extraData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.data)
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE GoogleSOCSCookie::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* released = _impl_.data_;
  _impl_.data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE GoogleSOCSCookie::unsafe_arena_release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.cookieBanner.GoogleSOCSCookie.data)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NONNULL GoogleSOCSCookie::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.data_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::mozilla::cookieBanner::GoogleSOCSCookie_extraData>(GetArena());
    _impl_.data_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_extraData*>(p);
  }
  return _impl_.data_;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NONNULL GoogleSOCSCookie::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_extraData* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:mozilla.cookieBanner.GoogleSOCSCookie.data)
  return _msg;
}
inline void GoogleSOCSCookie::set_allocated_data(::mozilla::cookieBanner::GoogleSOCSCookie_extraData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.data_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_extraData*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.data)
}

// required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
inline bool GoogleSOCSCookie::has_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.time_ != nullptr);
  return value;
}
inline void GoogleSOCSCookie::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_ != nullptr) _impl_.time_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData& GoogleSOCSCookie::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* p = _impl_.time_;
  return p != nullptr ? *p : reinterpret_cast<const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData&>(::mozilla::cookieBanner::_GoogleSOCSCookie_timeData_default_instance_);
}
inline const ::mozilla::cookieBanner::GoogleSOCSCookie_timeData& GoogleSOCSCookie::time() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.cookieBanner.GoogleSOCSCookie.time)
  return _internal_time();
}
inline void GoogleSOCSCookie::unsafe_arena_set_allocated_time(
    ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.time_);
  }
  _impl_.time_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_timeData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.time)
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE GoogleSOCSCookie::release_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* released = _impl_.time_;
  _impl_.time_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE GoogleSOCSCookie::unsafe_arena_release_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.cookieBanner.GoogleSOCSCookie.time)

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* temp = _impl_.time_;
  _impl_.time_ = nullptr;
  return temp;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NONNULL GoogleSOCSCookie::_internal_mutable_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::mozilla::cookieBanner::GoogleSOCSCookie_timeData>(GetArena());
    _impl_.time_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_timeData*>(p);
  }
  return _impl_.time_;
}
inline ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NONNULL GoogleSOCSCookie::mutable_time()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002U;
  ::mozilla::cookieBanner::GoogleSOCSCookie_timeData* _msg = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:mozilla.cookieBanner.GoogleSOCSCookie.time)
  return _msg;
}
inline void GoogleSOCSCookie::set_allocated_time(::mozilla::cookieBanner::GoogleSOCSCookie_timeData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.time_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }

  _impl_.time_ = reinterpret_cast<::mozilla::cookieBanner::GoogleSOCSCookie_timeData*>(value);
  // @@protoc_insertion_point(field_set_allocated:mozilla.cookieBanner.GoogleSOCSCookie.time)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cookieBanner
}  // namespace mozilla


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cookieBanner_2eproto_2epb_2eh
