// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cookieBanner.proto
// Protobuf C++ Version: 6.32.1

#include "cookieBanner.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mozilla {
namespace cookieBanner {

inline constexpr GoogleSOCSCookie_timeData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR GoogleSOCSCookie_timeData::GoogleSOCSCookie_timeData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(GoogleSOCSCookie_timeData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GoogleSOCSCookie_timeDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GoogleSOCSCookie_timeDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GoogleSOCSCookie_timeDataDefaultTypeInternal() {}
  union {
    GoogleSOCSCookie_timeData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GoogleSOCSCookie_timeDataDefaultTypeInternal _GoogleSOCSCookie_timeData_default_instance_;

inline constexpr GoogleSOCSCookie_extraData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        platform_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        region_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        unused1_{0u},
        unused2_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR GoogleSOCSCookie_extraData::GoogleSOCSCookie_extraData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(GoogleSOCSCookie_extraData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GoogleSOCSCookie_extraDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GoogleSOCSCookie_extraDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GoogleSOCSCookie_extraDataDefaultTypeInternal() {}
  union {
    GoogleSOCSCookie_extraData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GoogleSOCSCookie_extraDataDefaultTypeInternal _GoogleSOCSCookie_extraData_default_instance_;

inline constexpr GoogleSOCSCookie::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_{nullptr},
        time_{nullptr},
        gdpr_choice_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR GoogleSOCSCookie::GoogleSOCSCookie(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(GoogleSOCSCookie_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GoogleSOCSCookieDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GoogleSOCSCookieDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GoogleSOCSCookieDefaultTypeInternal() {}
  union {
    GoogleSOCSCookie _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GoogleSOCSCookieDefaultTypeInternal _GoogleSOCSCookie_default_instance_;
}  // namespace cookieBanner
}  // namespace mozilla
namespace mozilla {
namespace cookieBanner {
// ===================================================================

class GoogleSOCSCookie_extraData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GoogleSOCSCookie_extraData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000f) ^ 0x0000000f) != 0;
  }
};

GoogleSOCSCookie_extraData::GoogleSOCSCookie_extraData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_extraData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
}
PROTOBUF_NDEBUG_INLINE GoogleSOCSCookie_extraData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::mozilla::cookieBanner::GoogleSOCSCookie_extraData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        platform_(arena, from.platform_),
        region_(arena, from.region_) {}

GoogleSOCSCookie_extraData::GoogleSOCSCookie_extraData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GoogleSOCSCookie_extraData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_extraData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GoogleSOCSCookie_extraData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unused1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, unused1_),
           offsetof(Impl_, unused2_) -
               offsetof(Impl_, unused1_) +
               sizeof(Impl_::unused2_));

  // @@protoc_insertion_point(copy_constructor:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
}
PROTOBUF_NDEBUG_INLINE GoogleSOCSCookie_extraData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        platform_(arena),
        region_(arena) {}

inline void GoogleSOCSCookie_extraData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unused1_),
           0,
           offsetof(Impl_, unused2_) -
               offsetof(Impl_, unused1_) +
               sizeof(Impl_::unused2_));
}
GoogleSOCSCookie_extraData::~GoogleSOCSCookie_extraData() {
  // @@protoc_insertion_point(destructor:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  SharedDtor(*this);
}
inline void GoogleSOCSCookie_extraData::SharedDtor(MessageLite& self) {
  GoogleSOCSCookie_extraData& this_ = static_cast<GoogleSOCSCookie_extraData&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.platform_.Destroy();
  this_._impl_.region_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GoogleSOCSCookie_extraData(arena);
}
constexpr auto GoogleSOCSCookie_extraData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GoogleSOCSCookie_extraData),
                                            alignof(GoogleSOCSCookie_extraData));
}
constexpr auto GoogleSOCSCookie_extraData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<48>{
      {
          &_GoogleSOCSCookie_extraData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          GoogleSOCSCookie_extraData::IsInitializedImpl,
          &GoogleSOCSCookie_extraData::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<GoogleSOCSCookie_extraData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GoogleSOCSCookie_extraData::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<GoogleSOCSCookie_extraData>(), &GoogleSOCSCookie_extraData::ByteSizeLong,
              &GoogleSOCSCookie_extraData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_._cached_size_),
          true,
      },
      "mozilla.cookieBanner.GoogleSOCSCookie.extraData",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<48> GoogleSOCSCookie_extraData_class_data_ =
    GoogleSOCSCookie_extraData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GoogleSOCSCookie_extraData::GetClassData() const {
  return GoogleSOCSCookie_extraData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
GoogleSOCSCookie_extraData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GoogleSOCSCookie_extraData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mozilla::cookieBanner::GoogleSOCSCookie_extraData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint32 unused2 = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused2_)}},
    // required uint32 unused1 = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused1_)}},
    // required string platform = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.platform_)}},
    // required string region = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.region_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 unused1 = 1;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused1_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required string platform = 2;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.platform_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // required string region = 3;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.region_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // required uint32 unused2 = 4;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused2_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GoogleSOCSCookie_extraData::Clear() {
// @@protoc_insertion_point(message_clear_start:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.platform_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _impl_.region_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x0000000cU) != 0) {
    ::memset(&_impl_.unused1_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.unused2_) -
        reinterpret_cast<char*>(&_impl_.unused1_)) + sizeof(_impl_.unused2_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GoogleSOCSCookie_extraData& this_ = static_cast<const GoogleSOCSCookie_extraData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie_extraData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GoogleSOCSCookie_extraData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 unused1 = 1;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_unused1(), target);
  }

  // required string platform = 2;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_platform();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string region = 3;
  if ((cached_has_bits & 0x00000002U) != 0) {
    const ::std::string& _s = this_._internal_region();
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // required uint32 unused2 = 4;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_unused2(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GoogleSOCSCookie_extraData::ByteSizeLong(const MessageLite& base) {
  const GoogleSOCSCookie_extraData& this_ = static_cast<const GoogleSOCSCookie_extraData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GoogleSOCSCookie_extraData::ByteSizeLong() const {
  const GoogleSOCSCookie_extraData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    // required string platform = 2;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_platform());
    }
    // required string region = 3;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_region());
    }
    // required uint32 unused1 = 1;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_unused1());
    }
    // required uint32 unused2 = 4;
    if ((cached_has_bits & 0x00000008U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_unused2());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void GoogleSOCSCookie_extraData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GoogleSOCSCookie_extraData*>(&to_msg);
  auto& from = static_cast<const GoogleSOCSCookie_extraData&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_platform(from._internal_platform());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_internal_set_region(from._internal_region());
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.unused1_ = from._impl_.unused1_;
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _this->_impl_.unused2_ = from._impl_.unused2_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void GoogleSOCSCookie_extraData::CopyFrom(const GoogleSOCSCookie_extraData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mozilla.cookieBanner.GoogleSOCSCookie.extraData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GoogleSOCSCookie_extraData::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const GoogleSOCSCookie_extraData&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void GoogleSOCSCookie_extraData::InternalSwap(GoogleSOCSCookie_extraData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.platform_, &other->_impl_.platform_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.region_, &other->_impl_.region_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused2_)
      + sizeof(GoogleSOCSCookie_extraData::_impl_.unused2_)
      - PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_extraData, _impl_.unused1_)>(
          reinterpret_cast<char*>(&_impl_.unused1_),
          reinterpret_cast<char*>(&other->_impl_.unused1_));
}

// ===================================================================

class GoogleSOCSCookie_timeData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GoogleSOCSCookie_timeData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_timeData, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

GoogleSOCSCookie_timeData::GoogleSOCSCookie_timeData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_timeData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
}
GoogleSOCSCookie_timeData::GoogleSOCSCookie_timeData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GoogleSOCSCookie_timeData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_timeData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE GoogleSOCSCookie_timeData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GoogleSOCSCookie_timeData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
GoogleSOCSCookie_timeData::~GoogleSOCSCookie_timeData() {
  // @@protoc_insertion_point(destructor:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  SharedDtor(*this);
}
inline void GoogleSOCSCookie_timeData::SharedDtor(MessageLite& self) {
  GoogleSOCSCookie_timeData& this_ = static_cast<GoogleSOCSCookie_timeData&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GoogleSOCSCookie_timeData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GoogleSOCSCookie_timeData(arena);
}
constexpr auto GoogleSOCSCookie_timeData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GoogleSOCSCookie_timeData),
                                            alignof(GoogleSOCSCookie_timeData));
}
constexpr auto GoogleSOCSCookie_timeData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<47>{
      {
          &_GoogleSOCSCookie_timeData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          GoogleSOCSCookie_timeData::IsInitializedImpl,
          &GoogleSOCSCookie_timeData::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<GoogleSOCSCookie_timeData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GoogleSOCSCookie_timeData::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<GoogleSOCSCookie_timeData>(), &GoogleSOCSCookie_timeData::ByteSizeLong,
              &GoogleSOCSCookie_timeData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_timeData, _impl_._cached_size_),
          true,
      },
      "mozilla.cookieBanner.GoogleSOCSCookie.timeData",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<47> GoogleSOCSCookie_timeData_class_data_ =
    GoogleSOCSCookie_timeData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GoogleSOCSCookie_timeData::GetClassData() const {
  return GoogleSOCSCookie_timeData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
GoogleSOCSCookie_timeData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_timeData, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GoogleSOCSCookie_timeData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mozilla::cookieBanner::GoogleSOCSCookie_timeData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint64 timeStamp = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_timeData, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint64 timeStamp = 1;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie_timeData, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GoogleSOCSCookie_timeData::Clear() {
// @@protoc_insertion_point(message_clear_start:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timestamp_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie_timeData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GoogleSOCSCookie_timeData& this_ = static_cast<const GoogleSOCSCookie_timeData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie_timeData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GoogleSOCSCookie_timeData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint64 timeStamp = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_timestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GoogleSOCSCookie_timeData::ByteSizeLong(const MessageLite& base) {
  const GoogleSOCSCookie_timeData& this_ = static_cast<const GoogleSOCSCookie_timeData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GoogleSOCSCookie_timeData::ByteSizeLong() const {
  const GoogleSOCSCookie_timeData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // required uint64 timeStamp = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_timestamp());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void GoogleSOCSCookie_timeData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GoogleSOCSCookie_timeData*>(&to_msg);
  auto& from = static_cast<const GoogleSOCSCookie_timeData&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void GoogleSOCSCookie_timeData::CopyFrom(const GoogleSOCSCookie_timeData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mozilla.cookieBanner.GoogleSOCSCookie.timeData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GoogleSOCSCookie_timeData::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const GoogleSOCSCookie_timeData&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void GoogleSOCSCookie_timeData::InternalSwap(GoogleSOCSCookie_timeData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

// ===================================================================

class GoogleSOCSCookie::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GoogleSOCSCookie>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

GoogleSOCSCookie::GoogleSOCSCookie(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mozilla.cookieBanner.GoogleSOCSCookie)
}
PROTOBUF_NDEBUG_INLINE GoogleSOCSCookie::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::mozilla::cookieBanner::GoogleSOCSCookie& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GoogleSOCSCookie::GoogleSOCSCookie(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GoogleSOCSCookie& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, GoogleSOCSCookie_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GoogleSOCSCookie* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = ((cached_has_bits & 0x00000001U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.data_)
                : nullptr;
  _impl_.time_ = ((cached_has_bits & 0x00000002U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.time_)
                : nullptr;
  _impl_.gdpr_choice_ = from._impl_.gdpr_choice_;

  // @@protoc_insertion_point(copy_constructor:mozilla.cookieBanner.GoogleSOCSCookie)
}
PROTOBUF_NDEBUG_INLINE GoogleSOCSCookie::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GoogleSOCSCookie::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, data_),
           0,
           offsetof(Impl_, gdpr_choice_) -
               offsetof(Impl_, data_) +
               sizeof(Impl_::gdpr_choice_));
}
GoogleSOCSCookie::~GoogleSOCSCookie() {
  // @@protoc_insertion_point(destructor:mozilla.cookieBanner.GoogleSOCSCookie)
  SharedDtor(*this);
}
inline void GoogleSOCSCookie::SharedDtor(MessageLite& self) {
  GoogleSOCSCookie& this_ = static_cast<GoogleSOCSCookie&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.data_;
  delete this_._impl_.time_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GoogleSOCSCookie::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GoogleSOCSCookie(arena);
}
constexpr auto GoogleSOCSCookie::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GoogleSOCSCookie),
                                            alignof(GoogleSOCSCookie));
}
constexpr auto GoogleSOCSCookie::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<38>{
      {
          &_GoogleSOCSCookie_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          GoogleSOCSCookie::IsInitializedImpl,
          &GoogleSOCSCookie::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<GoogleSOCSCookie>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GoogleSOCSCookie::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<GoogleSOCSCookie>(), &GoogleSOCSCookie::ByteSizeLong,
              &GoogleSOCSCookie::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_._cached_size_),
          true,
      },
      "mozilla.cookieBanner.GoogleSOCSCookie",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<38> GoogleSOCSCookie_class_data_ =
    GoogleSOCSCookie::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GoogleSOCSCookie::GetClassData() const {
  return GoogleSOCSCookie_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2>
GoogleSOCSCookie::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GoogleSOCSCookie_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mozilla::cookieBanner::GoogleSOCSCookie>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required uint32 gdpr_choice = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.gdpr_choice_)}},
    // required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.data_)}},
    // required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 gdpr_choice = 1;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.gdpr_choice_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.data_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
    {PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.time_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::mozilla::cookieBanner::GoogleSOCSCookie_extraData>()},
      {::_pbi::TcParser::GetTable<::mozilla::cookieBanner::GoogleSOCSCookie_timeData>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GoogleSOCSCookie::Clear() {
// @@protoc_insertion_point(message_clear_start:mozilla.cookieBanner.GoogleSOCSCookie)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(_impl_.time_ != nullptr);
      _impl_.time_->Clear();
    }
  }
  _impl_.gdpr_choice_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GoogleSOCSCookie& this_ = static_cast<const GoogleSOCSCookie&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GoogleSOCSCookie::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GoogleSOCSCookie& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:mozilla.cookieBanner.GoogleSOCSCookie)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 gdpr_choice = 1;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_gdpr_choice(), target);
  }

  // required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.data_, this_._impl_.data_->GetCachedSize(), target,
        stream);
  }

  // required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.time_, this_._impl_.time_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mozilla.cookieBanner.GoogleSOCSCookie)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GoogleSOCSCookie::ByteSizeLong(const MessageLite& base) {
  const GoogleSOCSCookie& this_ = static_cast<const GoogleSOCSCookie&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GoogleSOCSCookie::ByteSizeLong() const {
  const GoogleSOCSCookie& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:mozilla.cookieBanner.GoogleSOCSCookie)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // required .mozilla.cookieBanner.GoogleSOCSCookie.extraData data = 2;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.data_);
    }
    // required .mozilla.cookieBanner.GoogleSOCSCookie.timeData time = 3;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.time_);
    }
    // required uint32 gdpr_choice = 1;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_gdpr_choice());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void GoogleSOCSCookie::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GoogleSOCSCookie*>(&to_msg);
  auto& from = static_cast<const GoogleSOCSCookie&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:mozilla.cookieBanner.GoogleSOCSCookie)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(from._impl_.data_ != nullptr);
      if (_this->_impl_.data_ == nullptr) {
        _this->_impl_.data_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.data_);
      } else {
        _this->_impl_.data_->MergeFrom(*from._impl_.data_);
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(from._impl_.time_ != nullptr);
      if (_this->_impl_.time_ == nullptr) {
        _this->_impl_.time_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.time_);
      } else {
        _this->_impl_.time_->MergeFrom(*from._impl_.time_);
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.gdpr_choice_ = from._impl_.gdpr_choice_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void GoogleSOCSCookie::CopyFrom(const GoogleSOCSCookie& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mozilla.cookieBanner.GoogleSOCSCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GoogleSOCSCookie::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const GoogleSOCSCookie&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._impl_.data_->IsInitialized()) return false;
  }
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (!this_._impl_.time_->IsInitialized()) return false;
  }
  return true;
}

void GoogleSOCSCookie::InternalSwap(GoogleSOCSCookie* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.gdpr_choice_)
      + sizeof(GoogleSOCSCookie::_impl_.gdpr_choice_)
      - PROTOBUF_FIELD_OFFSET(GoogleSOCSCookie, _impl_.data_)>(
          reinterpret_cast<char*>(&_impl_.data_),
          reinterpret_cast<char*>(&other->_impl_.data_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace cookieBanner
}  // namespace mozilla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
