// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fetch_msg_types.proto
// Protobuf C++ Version: 6.32.1

#ifndef fetch_5fmsg_5ftypes_2eproto_2epb_2eh
#define fetch_5fmsg_5ftypes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_field_lite.h"
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_fetch_5fmsg_5ftypes_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_fetch_5fmsg_5ftypes_2eproto {
  static const ::uint32_t offsets[];
};
namespace mozilla {
namespace appservices {
namespace httpconfig {
namespace protobuf {
enum Request_Method : int;
extern const uint32_t Request_Method_internal_data_[];
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<48> Request_class_data_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<49> Response_class_data_;
}  // namespace protobuf
}  // namespace httpconfig
}  // namespace appservices
}  // namespace mozilla
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::mozilla::appservices::httpconfig::protobuf::Request_Method_internal_data_>
    internal::EnumTraitsImpl::value<::mozilla::appservices::httpconfig::protobuf::Request_Method>;
}  // namespace protobuf
}  // namespace google

namespace mozilla {
namespace appservices {
namespace httpconfig {
namespace protobuf {
enum Request_Method : int {
  Request_Method_GET = 0,
  Request_Method_HEAD = 1,
  Request_Method_POST = 2,
  Request_Method_PUT = 3,
  Request_Method_DELETE = 4,
  Request_Method_CONNECT = 5,
  Request_Method_OPTIONS = 6,
  Request_Method_TRACE = 7,
  Request_Method_PATCH = 8,
};

extern const uint32_t Request_Method_internal_data_[];
inline constexpr Request_Method Request_Method_Method_MIN =
    static_cast<Request_Method>(0);
inline constexpr Request_Method Request_Method_Method_MAX =
    static_cast<Request_Method>(8);
inline bool Request_Method_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int Request_Method_Method_ARRAYSIZE = 8 + 1;
const ::std::string& Request_Method_Name(Request_Method value);
template <typename T>
const ::std::string& Request_Method_Name(T value) {
  static_assert(::std::is_same<T, Request_Method>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Method_Name().");
  return Request_Method_Name(static_cast<Request_Method>(value));
}
bool Request_Method_Parse(
    ::absl::string_view name, Request_Method* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

class Response final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:mozilla.appservices.httpconfig.protobuf.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Response(::google::protobuf::internal::ConstantInitialized);

  inline Response(const Response& from) : Response(nullptr, from) {}
  inline Response(Response&& from) noexcept
      : Response(nullptr, ::std::move(from)) {}
  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Response& default_instance() {
    return *reinterpret_cast<const Response*>(
        &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Response& a, Response& b) { a.Swap(&b); }
  inline void Swap(Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Response>(arena);
  }
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from) { Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozilla.appservices.httpconfig.protobuf.Response"; }

 protected:
  explicit Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Response& from);
  Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Response&& from) noexcept
      : Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeadersFieldNumber = 5,
    kExceptionMessageFieldNumber = 1,
    kUrlFieldNumber = 2,
    kBodyFieldNumber = 4,
    kStatusFieldNumber = 3,
  };
  // map<string, string> headers = 5;
  int headers_size() const;
  private:
  int _internal_headers_size() const;

  public:
  void clear_headers() ;
  const ::google::protobuf::Map<::std::string, ::std::string>& headers() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_headers();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_headers() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_headers();

  public:
  // optional string exception_message = 1;
  bool has_exception_message() const;
  void clear_exception_message() ;
  const ::std::string& exception_message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_exception_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_exception_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_exception_message();
  void set_allocated_exception_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_exception_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_exception_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_exception_message();

  public:
  // optional string url = 2;
  bool has_url() const;
  void clear_url() ;
  const ::std::string& url() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_url();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_url();
  void set_allocated_url(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_url() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_url(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_url();

  public:
  // optional bytes body = 4;
  bool has_body() const;
  void clear_body() ;
  const ::std::string& body() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_body(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_body();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_body();
  void set_allocated_body(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_body() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_body(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // optional int32 status = 3;
  bool has_status() const;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozilla.appservices.httpconfig.protobuf.Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 5,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapFieldLite<::std::string, ::std::string> headers_;
    ::google::protobuf::internal::ArenaStringPtr exception_message_;
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::google::protobuf::internal::ArenaStringPtr body_;
    ::int32_t status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fetch_5fmsg_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<49> Response_class_data_;
// -------------------------------------------------------------------

class Request final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:mozilla.appservices.httpconfig.protobuf.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Request(::google::protobuf::internal::ConstantInitialized);

  inline Request(const Request& from) : Request(nullptr, from) {}
  inline Request(Request&& from) noexcept
      : Request(nullptr, ::std::move(from)) {}
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Request& default_instance() {
    return *reinterpret_cast<const Request*>(
        &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Request& a, Request& b) { a.Swap(&b); }
  inline void Swap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Request>(arena);
  }
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from) { Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mozilla.appservices.httpconfig.protobuf.Request"; }

 protected:
  explicit Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Request& from);
  Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Request&& from) noexcept
      : Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using Method = Request_Method;
  static constexpr Method GET = Request_Method_GET;
  static constexpr Method HEAD = Request_Method_HEAD;
  static constexpr Method POST = Request_Method_POST;
  static constexpr Method PUT = Request_Method_PUT;
  static constexpr Method DELETE = Request_Method_DELETE;
  static constexpr Method CONNECT = Request_Method_CONNECT;
  static constexpr Method OPTIONS = Request_Method_OPTIONS;
  static constexpr Method TRACE = Request_Method_TRACE;
  static constexpr Method PATCH = Request_Method_PATCH;
  static inline bool Method_IsValid(int value) {
    return Request_Method_IsValid(value);
  }
  static constexpr Method Method_MIN = Request_Method_Method_MIN;
  static constexpr Method Method_MAX = Request_Method_Method_MAX;
  static constexpr int Method_ARRAYSIZE = Request_Method_Method_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& Method_Name(T value) {
    return Request_Method_Name(value);
  }
  static inline bool Method_Parse(
      ::absl::string_view name, Method* PROTOBUF_NONNULL value) {
    return Request_Method_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kHeadersFieldNumber = 4,
    kUrlFieldNumber = 2,
    kBodyFieldNumber = 3,
    kMethodFieldNumber = 1,
    kFollowRedirectsFieldNumber = 5,
    kUseCachesFieldNumber = 6,
    kConnectTimeoutSecsFieldNumber = 7,
    kReadTimeoutSecsFieldNumber = 8,
  };
  // map<string, string> headers = 4;
  int headers_size() const;
  private:
  int _internal_headers_size() const;

  public:
  void clear_headers() ;
  const ::google::protobuf::Map<::std::string, ::std::string>& headers() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_headers();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_headers() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_headers();

  public:
  // required string url = 2;
  bool has_url() const;
  void clear_url() ;
  const ::std::string& url() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_url();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_url();
  void set_allocated_url(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_url() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_url(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_url();

  public:
  // optional bytes body = 3;
  bool has_body() const;
  void clear_body() ;
  const ::std::string& body() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_body(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_body();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_body();
  void set_allocated_body(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_body() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_body(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // required .mozilla.appservices.httpconfig.protobuf.Request.Method method = 1;
  bool has_method() const;
  void clear_method() ;
  ::mozilla::appservices::httpconfig::protobuf::Request_Method method() const;
  void set_method(::mozilla::appservices::httpconfig::protobuf::Request_Method value);

  private:
  ::mozilla::appservices::httpconfig::protobuf::Request_Method _internal_method() const;
  void _internal_set_method(::mozilla::appservices::httpconfig::protobuf::Request_Method value);

  public:
  // required bool follow_redirects = 5;
  bool has_follow_redirects() const;
  void clear_follow_redirects() ;
  bool follow_redirects() const;
  void set_follow_redirects(bool value);

  private:
  bool _internal_follow_redirects() const;
  void _internal_set_follow_redirects(bool value);

  public:
  // required bool use_caches = 6;
  bool has_use_caches() const;
  void clear_use_caches() ;
  bool use_caches() const;
  void set_use_caches(bool value);

  private:
  bool _internal_use_caches() const;
  void _internal_set_use_caches(bool value);

  public:
  // required int32 connect_timeout_secs = 7;
  bool has_connect_timeout_secs() const;
  void clear_connect_timeout_secs() ;
  ::int32_t connect_timeout_secs() const;
  void set_connect_timeout_secs(::int32_t value);

  private:
  ::int32_t _internal_connect_timeout_secs() const;
  void _internal_set_connect_timeout_secs(::int32_t value);

  public:
  // required int32 read_timeout_secs = 8;
  bool has_read_timeout_secs() const;
  void clear_read_timeout_secs() ;
  ::int32_t read_timeout_secs() const;
  void set_read_timeout_secs(::int32_t value);

  private:
  ::int32_t _internal_read_timeout_secs() const;
  void _internal_set_read_timeout_secs(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mozilla.appservices.httpconfig.protobuf.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapFieldLite<::std::string, ::std::string> headers_;
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::google::protobuf::internal::ArenaStringPtr body_;
    int method_;
    bool follow_redirects_;
    bool use_caches_;
    ::int32_t connect_timeout_secs_;
    ::int32_t read_timeout_secs_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_fetch_5fmsg_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<48> Request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Request

// required .mozilla.appservices.httpconfig.protobuf.Request.Method method = 1;
inline bool Request::has_method() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void Request::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::mozilla::appservices::httpconfig::protobuf::Request_Method Request::method() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.method)
  return _internal_method();
}
inline void Request::set_method(::mozilla::appservices::httpconfig::protobuf::Request_Method value) {
  _internal_set_method(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.method)
}
inline ::mozilla::appservices::httpconfig::protobuf::Request_Method Request::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mozilla::appservices::httpconfig::protobuf::Request_Method>(_impl_.method_);
}
inline void Request::_internal_set_method(::mozilla::appservices::httpconfig::protobuf::Request_Method value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::mozilla::appservices::httpconfig::protobuf::Request_Method_internal_data_));
                                          _impl_.method_ = value;
}

// required string url = 2;
inline bool Request::has_url() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void Request::clear_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& Request::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.url)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Request::set_url(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.url)
}
inline ::std::string* PROTOBUF_NONNULL Request::mutable_url()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:mozilla.appservices.httpconfig.protobuf.Request.url)
  return _s;
}
inline const ::std::string& Request::_internal_url() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.url_.Get();
}
inline void Request::_internal_set_url(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.url_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Request::_internal_mutable_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.url_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Request::release_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.appservices.httpconfig.protobuf.Request.url)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.url_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.url_.Set("", GetArena());
  }
  return released;
}
inline void Request::set_allocated_url(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.url_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.appservices.httpconfig.protobuf.Request.url)
}

// optional bytes body = 3;
inline bool Request::has_body() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void Request::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& Request::body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.body)
  return _internal_body();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Request::set_body(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.body_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.body)
}
inline ::std::string* PROTOBUF_NONNULL Request::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:mozilla.appservices.httpconfig.protobuf.Request.body)
  return _s;
}
inline const ::std::string& Request::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_.Get();
}
inline void Request::_internal_set_body(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.body_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Request::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.body_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Request::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.appservices.httpconfig.protobuf.Request.body)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.body_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.body_.Set("", GetArena());
  }
  return released;
}
inline void Request::set_allocated_body(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.appservices.httpconfig.protobuf.Request.body)
}

// map<string, string> headers = 4;
inline int Request::_internal_headers_size() const {
  return _internal_headers().size();
}
inline int Request::headers_size() const {
  return _internal_headers_size();
}
inline void Request::clear_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headers_.Clear();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Request::_internal_headers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.headers_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Request::headers() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:mozilla.appservices.httpconfig.protobuf.Request.headers)
  return _internal_headers();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Request::_internal_mutable_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.headers_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Request::mutable_headers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:mozilla.appservices.httpconfig.protobuf.Request.headers)
  return _internal_mutable_headers();
}

// required bool follow_redirects = 5;
inline bool Request::has_follow_redirects() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void Request::clear_follow_redirects() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.follow_redirects_ = false;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline bool Request::follow_redirects() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.follow_redirects)
  return _internal_follow_redirects();
}
inline void Request::set_follow_redirects(bool value) {
  _internal_set_follow_redirects(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.follow_redirects)
}
inline bool Request::_internal_follow_redirects() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.follow_redirects_;
}
inline void Request::_internal_set_follow_redirects(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.follow_redirects_ = value;
}

// required bool use_caches = 6;
inline bool Request::has_use_caches() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010U) != 0;
  return value;
}
inline void Request::clear_use_caches() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_caches_ = false;
  _impl_._has_bits_[0] &= ~0x00000010U;
}
inline bool Request::use_caches() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.use_caches)
  return _internal_use_caches();
}
inline void Request::set_use_caches(bool value) {
  _internal_set_use_caches(value);
  _impl_._has_bits_[0] |= 0x00000010U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.use_caches)
}
inline bool Request::_internal_use_caches() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.use_caches_;
}
inline void Request::_internal_set_use_caches(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_caches_ = value;
}

// required int32 connect_timeout_secs = 7;
inline bool Request::has_connect_timeout_secs() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020U) != 0;
  return value;
}
inline void Request::clear_connect_timeout_secs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connect_timeout_secs_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020U;
}
inline ::int32_t Request::connect_timeout_secs() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.connect_timeout_secs)
  return _internal_connect_timeout_secs();
}
inline void Request::set_connect_timeout_secs(::int32_t value) {
  _internal_set_connect_timeout_secs(value);
  _impl_._has_bits_[0] |= 0x00000020U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.connect_timeout_secs)
}
inline ::int32_t Request::_internal_connect_timeout_secs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.connect_timeout_secs_;
}
inline void Request::_internal_set_connect_timeout_secs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connect_timeout_secs_ = value;
}

// required int32 read_timeout_secs = 8;
inline bool Request::has_read_timeout_secs() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040U) != 0;
  return value;
}
inline void Request::clear_read_timeout_secs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.read_timeout_secs_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040U;
}
inline ::int32_t Request::read_timeout_secs() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Request.read_timeout_secs)
  return _internal_read_timeout_secs();
}
inline void Request::set_read_timeout_secs(::int32_t value) {
  _internal_set_read_timeout_secs(value);
  _impl_._has_bits_[0] |= 0x00000040U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Request.read_timeout_secs)
}
inline ::int32_t Request::_internal_read_timeout_secs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.read_timeout_secs_;
}
inline void Request::_internal_set_read_timeout_secs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.read_timeout_secs_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Response

// optional string exception_message = 1;
inline bool Response::has_exception_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void Response::clear_exception_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exception_message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& Response::exception_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Response.exception_message)
  return _internal_exception_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Response::set_exception_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.exception_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Response.exception_message)
}
inline ::std::string* PROTOBUF_NONNULL Response::mutable_exception_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_exception_message();
  // @@protoc_insertion_point(field_mutable:mozilla.appservices.httpconfig.protobuf.Response.exception_message)
  return _s;
}
inline const ::std::string& Response::_internal_exception_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exception_message_.Get();
}
inline void Response::_internal_set_exception_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.exception_message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Response::_internal_mutable_exception_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.exception_message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Response::release_exception_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.appservices.httpconfig.protobuf.Response.exception_message)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.exception_message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.exception_message_.Set("", GetArena());
  }
  return released;
}
inline void Response::set_allocated_exception_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.exception_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.exception_message_.IsDefault()) {
    _impl_.exception_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.appservices.httpconfig.protobuf.Response.exception_message)
}

// optional string url = 2;
inline bool Response::has_url() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void Response::clear_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& Response::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Response.url)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Response::set_url(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Response.url)
}
inline ::std::string* PROTOBUF_NONNULL Response::mutable_url()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:mozilla.appservices.httpconfig.protobuf.Response.url)
  return _s;
}
inline const ::std::string& Response::_internal_url() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.url_.Get();
}
inline void Response::_internal_set_url(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.url_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Response::_internal_mutable_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.url_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Response::release_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.appservices.httpconfig.protobuf.Response.url)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.url_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.url_.Set("", GetArena());
  }
  return released;
}
inline void Response::set_allocated_url(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.url_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.appservices.httpconfig.protobuf.Response.url)
}

// optional int32 status = 3;
inline bool Response::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void Response::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::int32_t Response::status() const {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Response.status)
  return _internal_status();
}
inline void Response::set_status(::int32_t value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Response.status)
}
inline ::int32_t Response::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void Response::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// optional bytes body = 4;
inline bool Response::has_body() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void Response::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& Response::body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mozilla.appservices.httpconfig.protobuf.Response.body)
  return _internal_body();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Response::set_body(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.body_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mozilla.appservices.httpconfig.protobuf.Response.body)
}
inline ::std::string* PROTOBUF_NONNULL Response::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:mozilla.appservices.httpconfig.protobuf.Response.body)
  return _s;
}
inline const ::std::string& Response::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_.Get();
}
inline void Response::_internal_set_body(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.body_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Response::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.body_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Response::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mozilla.appservices.httpconfig.protobuf.Response.body)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.body_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.body_.Set("", GetArena());
  }
  return released;
}
inline void Response::set_allocated_body(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mozilla.appservices.httpconfig.protobuf.Response.body)
}

// map<string, string> headers = 5;
inline int Response::_internal_headers_size() const {
  return _internal_headers().size();
}
inline int Response::headers_size() const {
  return _internal_headers_size();
}
inline void Response::clear_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headers_.Clear();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Response::_internal_headers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.headers_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& Response::headers() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:mozilla.appservices.httpconfig.protobuf.Response.headers)
  return _internal_headers();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Response::_internal_mutable_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.headers_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL Response::mutable_headers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:mozilla.appservices.httpconfig.protobuf.Response.headers)
  return _internal_mutable_headers();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace httpconfig
}  // namespace appservices
}  // namespace mozilla


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mozilla::appservices::httpconfig::protobuf::Request_Method> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // fetch_5fmsg_5ftypes_2eproto_2epb_2eh
